version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  run-main-simulation:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - run:
          command: pipenv run python run_simulation_test.py
          name: Run Main Simulation
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

            - store_artifacts:
                path: /tmp/artifact-1
                destination: artifact-file

            - store_artifacts:
                path: /tmp/artifacts

workflows:
  main:
    jobs:
      - run-main-simulation