version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  run-main-simulation:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - run:
          command: pipenv run python ./run_simulation/run_simulation_test.py
          name: Run Main Simulation

workflows:
  main:
    jobs:
      - run-main-simulation
