version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  run-main-simulation:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Create temporary build artifacts directory
          command: mkdir /tmp/build-artifacts
      - run:
          name: Run Main Simulation
          command: pipenv run python run_simulation_test.py
      - store_artifacts:
          name: Upload results
          path: /tmp/build-artifacts/world-results.png

workflows:
  main:
    jobs:
      - run-main-simulation