version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  run-main-simulation:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run Main Simulation
          command: pipenv run python run_simulation_test.py
      - run:
          name: Upload Final World Image


workflows:
  main:
    jobs:
      - run-main-simulation